import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./components/CartProvider";
import AppearanceProvider from "./components/AppearanceProvider";

export const metadata: Metadata = {
  title: "YeHagere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <AppearanceProvider>
          <CartProvider>{children}</CartProvider>
        </AppearanceProvider>
      </body>
    </html>
  );
}
